// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

const myStoreLink = document.querySelector('#sidebar .side-menu.top li:nth-child(2) a');
const contentDiv = document.getElementById('content');

myStoreLink.addEventListener('click', function (event) {
  event.preventDefault(); // Empêche le comportement par défaut du lien

  // Mettre à jour le contenu de la div "content" avec le contenu de My Store
  contentDiv.innerHTML = `
  <!-- MAIN -->
  <main>
      <div class="head-title">
          <div class="left">
              <h1>Agents</h1>
              <ul class="breadcrumb">
                  <li>
                      <a href="#">Dashboard</a>
                  </li>
                  <li><i class='bx bx-chevron-right' ></i></li>
                  <li>
                      <a class="active" href="#">Home</a>
                  </li>
              </ul>
          </div>
          <a href="#" class="btn-download">
              <i class='bx bxs-cloud-download' ></i>
              <span class="text">Download PDF</span>
          </a>
      </div>


      <div class="table-data">
          <div class="order">
              <div class="head">
                  <h3>Recent Orders</h3>
                  <i class='bx bx-search' ></i>
                  <i class='bx bx-filter' ></i>
              </div>
              <table>
                  <thead>
                      <tr>
                          <th>Agents</th>
                          <th>Date</th>
                          <th>Status</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                          <td>
                              <img src="img/people.png">
                              <p>John Doe</p>
                          </td>
                          <td>01-10-2021</td>
                          <td><span class="status completed">Completed</span></td>
                      </tr>
                      <tr>
                          <td>
                              <img src="img/people.png">
                              <p>John Doe</p>
                          </td>
                          <td>01-10-2021</td>
                          <td><span class="status pending">Pending</span></td>
                      </tr>
                      <tr>
                          <td>
                              <img src="img/people.png">
                              <p>John Doe</p>
                          </td>
                          <td>01-10-2021</td>
                          <td><span class="status process">Process</span></td>
                      </tr>
                      <tr>
                          <td>
                              <img src="img/people.png">
                              <p>John Doe</p>
                          </td>
                          <td>01-10-2021</td>
                          <td><span class="status pending">Pending</span></td>
                      </tr>
                      <tr>
                          <td>
                              <img src="img/people.png">
                              <p>John Doe</p>
                          </td>
                          <td>01-10-2021</td>
                          <td><span class="status completed">Completed</span></td>
                      </tr>
                  </tbody>
              </table>
          </div>
          <div class="todo">
              <div class="head">
                  <h3>Todos</h3>
                  <i class='bx bx-plus' ></i>
                  <i class='bx bx-filter' ></i>
              </div>
              <ul class="todo-list">
                  <li class="completed">
                      <p>Todo List</p>
                      <i class='bx bx-dots-vertical-rounded' ></i>
                  </li>
                  <li class="completed">
                      <p>Todo List</p>
                      <i class='bx bx-dots-vertical-rounded' ></i>
                  </li>
                  <li class="not-completed">
                      <p>Todo List</p>
                      <i class='bx bx-dots-vertical-rounded' ></i>
                  </li>
                  <li class="completed">
                      <p>Todo List</p>
                      <i class='bx bx-dots-vertical-rounded' ></i>
                  </li>
                  <li class="not-completed">
                      <p>Todo List</p>
                      <i class='bx bx-dots-vertical-rounded' ></i>
                  </li>
              </ul>
          </div>
      </div>
  </main>
  <!-- MAIN -->
  `;

  // Mettre à jour la classe active dans la barre latérale
  const activeItem = document.querySelector('#sidebar .side-menu.top li.active');
  activeItem.classList.remove('active');
  this.parentElement.classList.add('active');
});


const dashboardLink = document.querySelector('#sidebar .side-menu.top li:nth-child(1) a');

dashboardLink.addEventListener('click', function (event) {
  event.preventDefault(); // Empêche le comportement par défaut du lien

  // Mettre à jour le contenu de la div "content" avec le contenu du Dashboard
  contentDiv.innerHTML = `
  
    <!-- MAIN -->
    <main>
        <div class="head-title">
            <div class="left">
                <h1>Offres</h1>
                <ul class="breadcrumb">
                    <li>
                        <a href="#">Dashboard</a>
                    </li>
                    <li><i class='bx bx-chevron-right' ></i></li>
                    <li>
                        <a class="active" href="#">Home</a>
                    </li>
                </ul>
            </div>
            <a href="#" class="btn-download">
                <i class='bx bxs-cloud-download' ></i>
                <span class="text">Download PDF</span>
            </a>
        </div>


        <div class="table-data">
            <div class="order">
                <div class="head">
                    <h3>Recent Orders</h3>
                    <i class='bx bx-search' ></i>
                    <i class='bx bx-filter' ></i>
                </div>
                <table>
                    <thead>
                        <tr>
                            <th>User</th>
                            <th>Date Order</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <!-- <img src="img/people.png"> -->
                                <p>John Doe</p>
                            </td>
                            <td>01-10-2021</td>
                            <td><span class="status completed">Completed</span></td>
                        </tr>
                        <tr>
                            <td>
                                <!-- <img src="img/people.png"> -->
                                <p>John Doe</p>
                            </td>
                            <td>01-10-2021</td>
                            <td><span class="status pending">Pending</span></td>
                        </tr>
                        <tr>
                            <td>
                                <!-- <img src="img/people.png"> -->
                                <p>John Doe</p>
                            </td>
                            <td>01-10-2021</td>
                            <td><span class="status process">Process</span></td>
                        </tr>
                        <tr>
                            <td>
                                <!-- <img src="img/people.png"> -->
                                <p>John Doe</p>
                            </td>
                            <td>01-10-2021</td>
                            <td><span class="status pending">Pending</span></td>
                        </tr>
                        <tr>
                            <td>
                                <!-- <img src="img/people.png"> -->
                                <p>John Doe</p>
                            </td>
                            <td>01-10-2021</td>
                            <td><span class="status completed">Completed</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="todo">
                <div class="head">
                    <h3>Todos</h3>
                    <i class='bx bx-plus' ></i>
                    <i class='bx bx-filter' ></i>
                </div>
                <ul class="todo-list">
                    <li class="completed">
                        <p>Todo List</p>
                        <i class='bx bx-dots-vertical-rounded' ></i>
                    </li>
                    <li class="completed">
                        <p>Todo List</p>
                        <i class='bx bx-dots-vertical-rounded' ></i>
                    </li>
                    <li class="not-completed">
                        <p>Todo List</p>
                        <i class='bx bx-dots-vertical-rounded' ></i>
                    </li>
                    <li class="completed">
                        <p>Todo List</p>
                        <i class='bx bx-dots-vertical-rounded' ></i>
                    </li>
                    <li class="not-completed">
                        <p>Todo List</p>
                        <i class='bx bx-dots-vertical-rounded' ></i>
                    </li>
                </ul>
            </div>
        </div>
    </main>
    <!-- MAIN -->
  `;

  // Mettre à jour la classe active dans la barre latérale
  const activeItem = document.querySelector('#sidebar .side-menu.top li.active');
  activeItem.classList.remove('active');
  this.parentElement.classList.add('active');
});

